version: '3.7'

services:
  backend:
    build: ./
    ports:
      - "5000:5000"
    restart: on-failure:5
    env_file:
      - .env
    environment:
        FLASK_APP: ${FLASK_APP}
        FLASK_RUN_HOST: ${FLASK_RUN_HOST}
        FLASK_RUN_PORT: ${FLASK_RUN_PORT}
        FLASK_ENV: ${FLASK_ENV}
    volumes:
      - .:/bedata
  client:
    container_name: client
    build: ./src/client/
    links:
      - "backend"
    ports:
      - "8080:8080"
    volumes:
      - .:/code
    restart: on-failure:5
